[package]
name = "rimage"
version = "0.11.0-next"
edition = "2021"
description = "Optimize images natively with best-in-class codecs"
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Vladyslav Vladinov <vladinov.dev@gmail.com>"]
keywords = ["image", "compression", "encoder"]
categories = ["compression", "multimedia::images"]
repository = "https://github.com/SalOne22/rimage"
documentation = "https://docs.rs/rimage"
homepage = "https://lib.rs/rimage"
include = ["/README.md", "/Cargo.toml", "/src/**/*.rs"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["cargo", "string"] }
fast_image_resize = "3.0.4"
imagequant = "4.3.0"
indoc = "2.0.4"
log = "0.4.20"
pretty_env_logger = "0.5.0"
rayon = "1.8.1"
zune-core = "0.4.12"
zune-image = "0.4.15"
